<?php
namespace AAB\Extensions;

if (!defined('ABSPATH')) exit;

/**
 * SEO Statistics Calculator
 * 
 * Calculates SEO metrics for posts generated by AutoContent AI campaigns
 */
class SEOStats {
    
    /**
     * Get all SEO statistics for AutoContent AI posts
     * 
     * @return array Array of SEO statistics
     */
    public static function get_stats() {
        // Get all posts generated by AutoContent AI campaigns
        $aab_posts = get_posts([
            'post_type' => 'post',
            'meta_key' => 'aab_campaign_id',
            'meta_compare' => 'EXISTS',
            'post_status' => 'publish',
            'numberposts' => -1,
            'fields' => 'ids'
        ]);
        
        $total_posts = count($aab_posts);
        
        if ($total_posts === 0) {
            return [
                'total_posts' => 0,
                'with_seo_meta' => 0,
                'with_seo_meta_percentage' => 0,
                'complete_seo' => 0,
                'complete_seo_percentage' => 0,
                'with_schema' => 0,
                'with_schema_percentage' => 0,
                'with_social_tags' => 0,
                'with_social_tags_percentage' => 0,
                'with_internal_links' => 0,
                'with_internal_links_percentage' => 0,
                'seo_enabled_campaigns' => 0,
                'total_campaigns' => 0,
            ];
        }
        
        // Initialize counters
        $with_seo_meta = 0;
        $complete_seo = 0;
        $with_schema = 0;
        $with_social_tags = 0;
        $with_internal_links = 0;
        
        // Analyze each post
        foreach ($aab_posts as $post_id) {
            $has_title = self::has_meta_title($post_id);
            $has_description = self::has_meta_description($post_id);
            $has_schema = self::has_schema_markup($post_id);
            $has_social = self::has_social_tags($post_id);
            $has_links = self::has_internal_links($post_id);
            
            // Count posts with at least some SEO meta
            if ($has_title || $has_description) {
                $with_seo_meta++;
            }
            
            // Count posts with complete SEO (all fields present)
            if ($has_title && $has_description && $has_schema && $has_social) {
                $complete_seo++;
            }
            
            if ($has_schema) {
                $with_schema++;
            }
            
            if ($has_social) {
                $with_social_tags++;
            }
            
            if ($has_links) {
                $with_internal_links++;
            }
        }
        
        // Get campaign statistics
        $campaign_stats = self::get_campaign_stats();
        
        return [
            'total_posts' => $total_posts,
            'with_seo_meta' => $with_seo_meta,
            'with_seo_meta_percentage' => $total_posts > 0 ? round(($with_seo_meta / $total_posts) * 100) : 0,
            'complete_seo' => $complete_seo,
            'complete_seo_percentage' => $total_posts > 0 ? round(($complete_seo / $total_posts) * 100) : 0,
            'with_schema' => $with_schema,
            'with_schema_percentage' => $total_posts > 0 ? round(($with_schema / $total_posts) * 100) : 0,
            'with_social_tags' => $with_social_tags,
            'with_social_tags_percentage' => $total_posts > 0 ? round(($with_social_tags / $total_posts) * 100) : 0,
            'with_internal_links' => $with_internal_links,
            'with_internal_links_percentage' => $total_posts > 0 ? round(($with_internal_links / $total_posts) * 100) : 0,
            'seo_enabled_campaigns' => $campaign_stats['seo_enabled'],
            'total_campaigns' => $campaign_stats['total'],
        ];
    }
    
    /**
     * Check if post has meta title (Yoast, Rank Math, or AIOSEO)
     */
    private static function has_meta_title($post_id) {
        $yoast_title = get_post_meta($post_id, '_yoast_wpseo_title', true);
        $rank_math_title = get_post_meta($post_id, 'rank_math_title', true);
        $aioseo_title = get_post_meta($post_id, '_aioseo_title', true);
        
        return !empty($yoast_title) || !empty($rank_math_title) || !empty($aioseo_title);
    }
    
    /**
     * Check if post has meta description (Yoast, Rank Math, or AIOSEO)
     */
    private static function has_meta_description($post_id) {
        $yoast_desc = get_post_meta($post_id, '_yoast_wpseo_metadesc', true);
        $rank_math_desc = get_post_meta($post_id, 'rank_math_description', true);
        $aioseo_desc = get_post_meta($post_id, '_aioseo_description', true);
        
        return !empty($yoast_desc) || !empty($rank_math_desc) || !empty($aioseo_desc);
    }
    
    /**
     * Check if post has schema markup capability
     * (Based on campaign SEO settings)
     */
    private static function has_schema_markup($post_id) {
        $campaign_id = get_post_meta($post_id, 'aab_campaign_id', true);
        if (!$campaign_id) {
            return false;
        }
        
        // Check if SEO is enabled for this campaign (schema is auto-added if SEO is enabled)
        $seo_enabled = get_post_meta($campaign_id, 'aab_seo_enabled', true);
        return (bool) $seo_enabled;
    }
    
    /**
     * Check if post has social tags capability
     * (Based on campaign SEO settings)
     */
    private static function has_social_tags($post_id) {
        $campaign_id = get_post_meta($post_id, 'aab_campaign_id', true);
        if (!$campaign_id) {
            return false;
        }
        
        // Check if social meta is enabled (or if SEO is enabled, as social tags are default)
        $social_enabled = get_post_meta($campaign_id, 'aab_seo_social_meta', true);
        $seo_enabled = get_post_meta($campaign_id, 'aab_seo_enabled', true);
        
        return (bool) $social_enabled || (bool) $seo_enabled;
    }
    
    /**
     * Check if post has internal links
     * (Based on campaign settings)
     */
    private static function has_internal_links($post_id) {
        $campaign_id = get_post_meta($post_id, 'aab_campaign_id', true);
        if (!$campaign_id) {
            return false;
        }
        
        // Check if internal linking is enabled for this campaign
        $internal_links_enabled = get_post_meta($campaign_id, 'aab_seo_internal_links', true);
        return (bool) $internal_links_enabled;
    }
    
    /**
     * Get campaign statistics (SEO-enabled vs total)
     */
    private static function get_campaign_stats() {
        $campaigns = get_posts([
            'post_type' => 'aab_campaign',
            'post_status' => 'publish',
            'numberposts' => -1,
            'fields' => 'ids'
        ]);
        
        $total = count($campaigns);
        $seo_enabled = 0;
        
        foreach ($campaigns as $campaign_id) {
            if (get_post_meta($campaign_id, 'aab_seo_enabled', true)) {
                $seo_enabled++;
            }
        }
        
        return [
            'total' => $total,
            'seo_enabled' => $seo_enabled,
        ];
    }
    
    /**
     * Get SEO health score (0-100)
     * Based on percentage of posts with complete SEO
     */
    public static function get_health_score() {
        $stats = self::get_stats();
        
        if ($stats['total_posts'] === 0) {
            return 0;
        }
        
        // Weighted scoring
        $score = 0;
        $score += $stats['with_seo_meta_percentage'] * 0.3; // 30% weight
        $score += $stats['complete_seo_percentage'] * 0.3;  // 30% weight
        $score += $stats['with_schema_percentage'] * 0.2;    // 20% weight
        $score += $stats['with_social_tags_percentage'] * 0.2; // 20% weight
        
        return round($score);
    }
}
